### ISSUE TITLE
Write python-scripts to print Dymo labels -- send bash commands? DEADLINE:

### ISSUE THREAD

**Issue by michaelplews** [canismarko/professor_oak#48]

**Comment by canismarko** [comment]
Are we actually targeting Dymo integration for the initial release or can we move this to future development

**Comment by michaelplews** [comment]
If we don't its just one more thing for everyone to have to 'get used to' upon later releases. I'd like to have this released with the initial launch so we avoid anyone 'just not doing it'.

**Comment by michaelplews** [comment]
I have to do this by installing a tarball. Where should I do this in geodudes directory? Or should I already know that?

**Comment by canismarko** [comment]
To start with I would work in your home directory /home/<USERNAME> then
when you're ready to pull the trigger, make a new directory in /srv,
unless there are other requirements in your instructions.

-Mark

**Comment by michaelplews** [comment]
Ok. The webSDK thing didn't work because it doesn't come with javascript printing. only printing plain text on a label which isn't what we wanted. I managed to design a label and print it from the command line from the container information supplied in a .csv file (which can be easily created with python). I think I'll have geodude produce the csv file and send it to the pi. Then the pi can follow up with these three bash commands.

`glabels-3-batch --input=example.csv gLabelsTest.glabels --output=output.pdf`
`lp -d DYMO_LabelWriter_450 output.pdf`
`rm output.pdf`

The other option would be to have geodude do all this and just print to the pi as a cups server.

So my question is: does gLabels come pre-installed on Debain? If not, would it be a hassle to install? Is there a way to script bash / linux commands?

Edit: if we did do all these on geodude, we have the option of saving the pdf of the label files, meaning we could display them and reprint them with minimal server effort.

**Comment by canismarko** [comment]
It's not pre-installed, but glabels is in the official debian
repositories so it will be straightforward to install. It does have a
lot of dependencies, many of which may already be installed on a pi but
are not on Geodude, since the pi already has a desktop-environment by
default.

Yes, BASH is actually a scripting language in itself. Just make a text
file with your three commands in it (one per line) and then run `chmod
755 <filename>` to make it executable. Alternately, you just call each
command one after another in python using `subprocess.call`.
