### ISSUE TITLE
Formatting and progress bars to individual user pages?

### ISSUE THREAD

**Issue by michaelplews** [canismarko/professor_oak#73]
Could we make it look a little more user friendly with [bootstrap progress bars](http://getbootstrap.com/components/#progress) to show how up to date you are with your assigned chemicals? 

Or would this look a little too adolescent?

**Comment by canismarko** [comment]
Only one way to find out... =P

Sounds like a good idea to me.

**Comment by michaelplews** [comment]
Nice!

**Comment by canismarko** [comment]
Would you entertain the idea of having this be stacked bars with the denominator be the most owned containers of _any_ user? This would let us compare how many chemicals each user has as well as how good of a job they're doing.

For example, let's assume there's two users: Mark has 3 expired chemicals and 5 unexpired ones, Mike has 2 expired and 2 unexpired. The bars would look like this (R for red and G for green):

Mark:
**RRR**GGGGG
Mike:
**RR**GG--------

I think I came up with a slick way of doing this but don't want to implement it without your input since this was your feature.

**Comment by michaelplews** [comment]
I will be able to do it but it'll have to be with the 6 filters. I can't seem to trick Django into passing two arguments.

**Comment by michaelplews** [comment]
Aww yeah
