### ISSUE TITLE
Schedule for portable cyclers

### ISSUE THREAD

**Issue by canismarko** [canismarko/professor_oak#89]
I thought it might be a good idea to have a way to reserve the portable cyclers for beamtime. It's probably a significant feature since we'll need calendar and scheduling support, though maybe we can start out simple and build it up as necessary.

**Comment by michaelplews** [comment]
I like this idea, but struggle with the user experience when we have 32 channels, we can't have 32 calendars!

My initial thoughts for approach would be to make a Channel object in the Model. The user can then request time (perhaps a priority algorithm can be used if it's for beamtime) and have the server email the user its allotted time as well as the channel it will be using. The user doesn't need to choose the channel as that is arbitrary. It might be a good idea to roll this out on 8 channels to start with before rolling it out to all 32.

Future development could involve making each experiment an object, with an 'Experiment Finished' field, allowing users to be notified by the server, as well as the Channel knowing when it's free rather than blindly assuming it's when the user told it it would be. 

https://github.com/llazzaro/django-scheduler

**Comment by canismarko** [comment]
Sounds like you're talking about the non-portable cycler (title says "portable"). Regardless, the portable cyclers hasn't been a problem IMO so let's just close it. I think the only way to make the big cycler scheduling work is to make it a part of the BTLab software, which is a whole other can of worms.
